[package]
name = "db_config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Momir Stanišić"]

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"