[package]
name = "compression"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Momir Stanišić"]

[dependencies]
bitvec = "1.0.1"

[dev-dependencies]
tempfile = "3.9.0"