[package]
name = "simhash"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Viktor Srbljin"]

[dependencies]
regex = "1.10.2"
twox-hash = "1.6.3"
phf = { version = "0.11", features = ["macros"] }
