[package]
name = "write_ahead_log"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Luka Bursać"]

[dependencies]
crc = "3.0.1"
segment_elements = { path = "../segment_elements" }