[package]
name = "lru_cache"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Mihajlo Orlovic"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
segment_elements = { path = "../segment_elements" }