[package]
name = "lru_cache"
version.workspace = true
edition.workspace = true
license.workspace = true
authors = ["Mihajlo Orlović"]

[dependencies]
segment_elements = { path = "../segment_elements" }